### PR TITLE
Create Run class with tests

### PR DESCRIPTION
**Pull request by dmin**
I've been thinking about how we might model a player's move. I still don't have a great answer, so I thought I would just write some code. The ```Run``` class models the idea of a group of tokens of the same color in sequential order.

This PR is just a basic implementation - there is no error handling when passing wrong arguments, and there is no validation that the changes to the run are actually allowed.

Let me know what you think @ashleymichal

### CODE REVIEW

**Comment by ashleymichal** [comment]
I think it's a decent place to start.  Two things I would change:
1. use attr_accessors to manipulate instance variables rather than manipulating them in place.
2. break 'change' out into 'add' and 'remove'

also in ln 23, array.delete(x) removes ALL instances of x in an array, which may lead to a bug since each tile is duplicated.

#2 and ln 23 lead me to this design question: once a run is created, in game I know you're allowed to ADD to an existing run, but are you allowed to remove tiles from a run on the board? Basically, where in gameplay would we need a 'remove' method?

**Comment by dmin** [comment]
> use attr_accessors to manipulate instance variables rather than manipulating them in place.

Good thought. Done. This brought my attention to possible future issues with sorting tokens in a ```Run```. I'm not sure if the sorting of tokens should be the responsibility of the ```Run``` class. It might make more sense for a class that displays ```Run```s to handle the sorting. For now I've left (fake) sorting in the ```Run``` class.

> break 'change' out into 'add' and 'remove'

Another good thought (which I feel should have been obvious to me! haha). My head was in front-end API land - trying to make the fewest possible API calls - but that should not be dealt with in the ```Run``` class. Done.

> In line 26, array.delete(x) removes ALL instances of x in an array, which may lead to a bug since each tile is duplicated.

What is not obvious in the code or the tests is that my intention was to have each ```Token``` be a unique object or have a unique id that we would use to compare tokens instead of comparing them by color/number. In the test I used symbols for simplicity and to keep the tests focused only on the ```Run``` class.

> In line 37, what is the purpose of returning 'nil' rather than an empty array for 0 tokens remaining in the run?

Again, my head was thinking in terms of how we would expose this to a front-end API.  When another object sends the ```remove``` message to a ```Run``` object I wanted to indicate to the caller that if all the tokens in the run had been removed then it should no longer be shown on the game board (since there are no tokens to show).

I agree that returning ```nil``` was never the best choice. I think we can kick this decision into the future. For now I updated both ```Run#add``` and ```Run#remove``` methods to return the updated list of 'ordered' tokens in the Run. I updated the tests for those methods to test the return values as well as the side-effect of changing the result of ```Run#tokens```.

> All that leads me to this design question: once a run is created, in game I know you're allowed to ADD to an existing run, but are you allowed to remove tiles from a run on the board? Basically, where in gameplay would we need a 'remove' method?

Yes - tokens can be removed from a run as long as that run still has 3 or more tokens left after you remove some, or if you add new tokens so that the total number of tokens remains 3 or greater.

**Comment by dmin** [comment]
We're already having git issues :grin: ha!  I couldn't figure out why I couldn't push my changes to this branch and why I would have merge conflicts - took me a few minutes to realize you had already pushed a new commit to this branch. So anyway, that's why I clobbered your last commit :astonished: sorry!

See issue #2 - I still need to read through that link my self - next time we talk we'll have to nail down whatever process we want to use.

**Comment by ashleymichal** [comment]
That's fully my bad. Fun learning time. SO the more appropriate thing to do would be to make the comments, let you fix them and resubmit the commit? It seems the less douchey way, lol, I apologize again.

**Comment by ashleymichal** [comment]
Also, while we're working through workflow logistics, here is what appears to be the closest thing to a "universal" Ruby style guide I can find on them internets:

https://github.com/bbatsov/ruby-style-guide

**Comment by dmin** [comment]
Yeah, (as far as I've seen) its typically best practice when reviewing someone else's code to just offer comments and let them make the changes. There are probably occasions where adding a commit to someone else's pull request is ok, but I think in general a PR branch should usually be considered "private" and owned by the creator of the pull request. Just what I've gathered so far, collaborating with people on code is new to me to!

**Comment by dmin** [comment]
Are you good with me merging this into master?

**Comment by ashleymichal** [comment]
Yes

On Wednesday, February 3, 2016, David Mininger <notifications@github.com>
wrote:

> Are you good with me merging this into master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rummikub/rummikub/pull/1#issuecomment-179442686>.
>


-- 
Ashley M Lewis
(512) 920 - 2248
https://www.linkedin.com/in/ashleymichal

**Comment by dmin** [comment]
I think it's typically good practice to delete merged branches from the github repository, so I deleted this branch now that is been merged. Your local copy of the repository is probably setup to "track" this (now deleted) branch, so if you delete it from your local repo it should remove all references to the now deleted branch on github. But I guess there's no harm in keeping it in your local repository if you really want to.

So many little things to think about with git! haha

**Pull request merged**
